```{r}
source("preamble.R")
```

# Chapter 4: Presentation of your results

**Objectives**

- Give careful thought into how to best show results in a understandable and
impactful way for public health professionals and clinicians.
- Emphasize figures over tables, but know when to use either.
- Be cautious in interpreting "non-significant" findings, since they could also
have meaningful clinical implications.
- Use cautious language when presenting results
    - Especially with "causal" language
- Discuss STROBE guidelines in context of longitudinal study.

- Sources of bias (not at this stage) TODO: move to analysis or wrangling chapter?

{{TODO: add another exercise expanding on making estimate more meaningful... maybe in Chapter 4?}}

- Know how to understand and interpret the results (we'll get to knowing what
exactly is most useful to present and show for higher impact) Or move to chapter 4?


## Lesson 1: Language and information to use when communicating the findings

- Danger of not showing all results or proper cautious interpretation, because
lives are at risk.
- Highlighting uncertainty and magnitude of results over "statistical significance"
- When to use stronger causal language
    - Depending on magnitude of finding, can use stronger causal language.
    - e.g. with smoking and lung cancer
    - Often argued that only Randomized Controlled Trials or animal/cell experiments 
    can use causal language, but that isn't always true.
    - Bradford Hill criteria (e.g. being smoking and lung cancer)
- Most of the time, your target audience for your results/analysis of cohort
studies is people in public health or government or clinicians... so you really
need to make sure that your results are *understandable* to *them*, not to other
data scientists or statisticians or epidemiologists (though you also need to 
target them).
- Discuss STROBE guidelines in context of longitudinal study.
    - Keep coming back to this throughout the chapter

**Exercises to reinforce learning:**

- MCQ/text: Which is the most appropriate language to use when describing these
results:
    - {large effect size} {strong causal language}
    - .. etc. fill out later.
- Do coding exercise with effect size then into comment about proper language.
    
### Exercise: Using causal or stronger "effect" language when discussing results

{{Bradford Hill *guideline* is also covered in the other epi courses... but
worth it to repeat since it is important}}

{{focus on these aspects: strength/effect size, consistency/replicability,
temporality, biological plausibility... these also apply to all aspects of causal
reasoning in all of science... even with all of these, may not be causal, but
have a common causal downstream factor.}}

Thinking about using stronger language


### Exercise: Using STROBE to guide presentation

{{MCE}}

Why is it important to present both unadjusted and adjusted models in your final
report (or slides, poster, or other publication outlet)?

- STROBE told me to do it, of course
- It's not important, only the adjusted models matter!
- Either unadjusted or adjusted can be biased, so need to show both {{expand/edit}}

## Lesson 2: Back transforming results for easier interpretation

- Backtransform based on what is most meaningful for presenting
- Types of backtransformation and impact on interpretation. (Should this be in
chapter 3?)
- Backtransforming for maximal interpretation and meaning
- STROBE guidelines
    - "consider translating estimates of relative risk into absolute risk for a
    meaningful time period"
    - Such as person years
