```{r setup}
source("preamble.R")
```

# Chapter 1: Introduction to cohorts and types of research questions

**Objectives:**

- Know that analyzing cohorts is just as much about the process/workflow as it
is about the specific tools/statistics to use.
- Recognize the type of cohort design from the data
- Know which research questions can and cannot be asked of the given data
- Have a general understand of which statistical tests to use for which data and
that the test will dictate how the data should look.
- Know where to look and what resources to use if you can't find the statistical
or analytical techniques needed to analyze the data.

## Lesson 1: Introduction to cohort designs

*Content:*

- Purpose of cohort studies ... why have them and what do they provide.
- Intro to some jargon:
    - cohorts
    - outcome
    - exposures
- Outline of course, focusing on workflow/process
- Types of cohort designs (mention that there are other types of these are most
common):
    - prospective (no exposure, no disease)
    - retrospective (exposure, but no disease)
- Type of design restricts type of analysis, so need to know the research
question and design
- Cohorts allow determining incidence, compared to prevalence

### Exercise: Which is which study type?

{{BulletExercise?}}

Usually the study design is explicitly stated in the study protocols, however,
it can be sometimes tricky to differentiate between the different cohort types.
Here are a couple examples of study collection protocols. Which protocols are
which study design?

### Exercise: When can prevalence or incidence be calculated? (maybe... or stick with below..?)

{{MCQ with console or NE?}}

The type of cohort design restricts what you can calculate. Using simple measures
such as `table` or `group_by` with `count`, which of the below responses are accurate?

{{Provide responses with possible numbers of prev/incid? Or just straight NE
to calculate incidence/prevalence?}}

### Exercise: What type of cohort design is this dataset? (maybe)

{{MCQ with console}}

Take a look at these datasets. {{very simply describe these datasets}}. What 
cohort designs are each of these datasets?

### Exercise: What study design is the Framingham Heart Study?

{{BulletExercise MCQ}}

Take a quick look at the dataset and research questions. Which study design is 
this cohort? What are the outcomes? And the exposures?

{{Include primary research question of original study}}

## Lesson 2: Introduction to the datasets and exploring them

*Content*
- Introduction to datasets we will use
- General look of data:
    - Show how the data looks:
        - baseline visit with disease status followup (time to disease, or age
        at diagnosis, or age at death, etc)
        - multiple data collection waves (ID and Wave columns)
        - Data will look very similar between prospective vs retrospective, the
        difference being how the data was collected... need to check what the
        variables mean, so need to refer to the documentation.
    - State assumptions first about the data (e.g. data already collected), this
    is not a course on how to conduct and collect cohort data.
- Variables: outcomes vs exposures/predictors

*Exercises*
- NE: Quickly look over data (simple, like head or something). Type out in order 
which is prospective, which is retrospective, etc.

### Exercise: Analytic and interpretation limitations of each study design

{{BulletExercise or TabExercise?}}

1. There are some analytic limitations to each study design. 
- MCQ/text: Limitation of retrospective over prospective (from an analytic and
interpretation point of view).
- MCQ/text: General limitations of prospective cohorts (again from analytic or
interpretation view)

### Exercise: Here's data and a question, which test to use? (maybe)

Text? or MCQ?: Show example data. Which statistics to use for this?
Or maybe choose which stats belongs with which data type? Or which question
belongs with which data and statistic?

## Lesson 3: Scientific questions that can be asked of cohort data

*Content*
- research questions able to be asked from data and impact on stats
    - retrospective, can ask questions like:
- {{Add more here}}
- types of questions we could ask of Framingham

*Exercises*
- MCQ/text: Given dataset, which questions can be asked based on data.
- MCQ/text: Which question needs which statistic? (hmm maybe not)
- Simpson's paradox? 

### Exercise 1:
Text? MCQ?: Which research question belongs with which dataset?

# Extra

- Sources of bias (not at this stage) TODO: move to analysis or wrangling chapter?
- odds ratio, relative risk, incidence rate ratio
    - risk estimate of some type, for instance of diseases that are not binary
    - which questions will need which statistic

{{Need some type of cliff hanger here...}}
