
# Chapter 2

**Objectives**

- Sources of bias (not at this stage) TODO: move to analysis or wrangling chapter?

- How to get data into form for quick exploration
- How to wrangle the data to get into a form to use for the analysis/statistic
- Know the various tools to transform the data and when is more appropriate to
use them
    - Know to be very careful of ever converting continuous into discrete
    - Know when and why to transform variables (good reasons and bad)
    - Reducing number of categories in categorical variable
- Dealing with outliers (or not)

## Lesson 1: Pre-wrangling exploration


## Lesson 2: Tidy cohort data and wrangling into analyzable form.

*Content*

For running models, each row should represent the all the values for one person
at one time point.

For plotting, the distributions of each variable, each row should represent one
variable for one person at one time point

*Exercises*
... maybe two waves that need to be combined?

## Lesson 3: Transforming and modifying variables (maybe into two lessons?)

*Content*


- Compare the distributions between the normal bmi and scaled bmi. What is different? WHy might scaling be useful?
- Compare the distributions between the normal bmi and the log bmi. What does logging do and why might it be useful?

# Notes:

- Look over data to find problems or fit to needs of research question
- Wrangling data to get into proper for statistics
- Transforming for statistics if necessary


