
library(tidyverse)
library(emojifont)
library(ghibli)
library(ggrepel)
library(patchwork)
library(rlang)
library(Epi)
library(DiagrammeR)
library(DiagrammeRsvg)
library(rsvg)
library(dagitty)
library(MuMIn)

data("diet")
color_theme <- ghibli_palette("MononokeMedium")
