
library(tidyverse)
library(emojifont)
library(ghibli)
library(ggrepel)
library(patchwork)
library(rlang)
library(DiagrammeR)
library(DiagrammeRsvg)
library(rsvg)
library(dagitty)
library(MuMIn)
library(janitor)
library(glue)
library(broom.mixed)
library(carpenter)
library(lme4)

color_theme <- ghibli_palette("MononokeMedium")
